name: Fetch Data

env:
  PROD_APPLICATION_ID: < PRODUCTION EMR Serverless Application ID >
  PROD_S3_BUCKET_NAME: < PRODUCTION S3 Bucket Name >
  JOB_ROLE_ARN: < EMR Serverless Job IAM Role >
  OIDC_ROLE_ARN: < GitHub OIDC IAM Role >
  AWS_REGION: us-east-1 < or any region you are using >
  JOB_VERSION: v0.0.1

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:
    inputs:
      job_version:
        description: 'What version (git tag) do you want to run?'
        required: false
        default: latest


jobs:
  github-views:
    runs-on: ubuntu-20.04
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./pyspark
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials from Prod account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
    
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ github.event.inputs.job_version == 'latest' }}
        with:
          semver_only: true

      - name: Start pyspark job
        run: |
          echo "running ${{ (steps.get-latest-tag.outputs.tag || github.event.inputs.job_version) || env.JOB_VERSION}} of our job"
          scripts/integration_test.sh $PROD_APPLICATION_ID $JOB_ROLE_ARN $PROD_S3_BUCKET_NAME ${{ (steps.get-latest-tag.outputs.tag || github.event.inputs.job_version) || env.JOB_VERSION}} main.py s3://${PROD_S3_BUCKET_NAME}/github/output/views/

